// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADx5YLqZldNGJFQd5xXFGSU2jnxsDCfU',
    appId: '1:343754509186:web:cfdfdd4f91ee3e2f3add9b',
    messagingSenderId: '343754509186',
    projectId: 'tubesppb-94f5f',
    authDomain: 'tubesppb-94f5f.firebaseapp.com',
    storageBucket: 'tubesppb-94f5f.appspot.com',
    measurementId: 'G-PD916R9JQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN-Q3bLxrkT-yE7H2bR9TtofyU4M5nilA',
    appId: '1:343754509186:android:6017d0381cd3214d3add9b',
    messagingSenderId: '343754509186',
    projectId: 'tubesppb-94f5f',
    storageBucket: 'tubesppb-94f5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZEJG68fzKjyZ3DDNhoRVxOEVKoMxlLE',
    appId: '1:343754509186:ios:7a07a693387545cc3add9b',
    messagingSenderId: '343754509186',
    projectId: 'tubesppb-94f5f',
    storageBucket: 'tubesppb-94f5f.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZEJG68fzKjyZ3DDNhoRVxOEVKoMxlLE',
    appId: '1:343754509186:ios:7a07a693387545cc3add9b',
    messagingSenderId: '343754509186',
    projectId: 'tubesppb-94f5f',
    storageBucket: 'tubesppb-94f5f.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAADx5YLqZldNGJFQd5xXFGSU2jnxsDCfU',
    appId: '1:343754509186:web:12a056ec8515929e3add9b',
    messagingSenderId: '343754509186',
    projectId: 'tubesppb-94f5f',
    authDomain: 'tubesppb-94f5f.firebaseapp.com',
    storageBucket: 'tubesppb-94f5f.appspot.com',
    measurementId: 'G-R572GX1ZSG',
  );

}