// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmxnIJmowzMq8l3bldYHLAaM1hNy2IzD4',
    appId: '1:299534401118:web:c6b9ed4e56420793ed3ecf',
    messagingSenderId: '299534401118',
    projectId: 'prakflutterfirebase-1373c',
    authDomain: 'prakflutterfirebase-1373c.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-1373c.appspot.com',
    measurementId: 'G-DR3CMZWVP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7jyCumZjphnXBAlGM8j4K6CXcfdmMNxQ',
    appId: '1:299534401118:android:048f000e469444f4ed3ecf',
    messagingSenderId: '299534401118',
    projectId: 'prakflutterfirebase-1373c',
    storageBucket: 'prakflutterfirebase-1373c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb7CEtKeXDFW1uDQhGyWNdCy49521vj6g',
    appId: '1:299534401118:ios:5c9ba44c8b8d376fed3ecf',
    messagingSenderId: '299534401118',
    projectId: 'prakflutterfirebase-1373c',
    storageBucket: 'prakflutterfirebase-1373c.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb7CEtKeXDFW1uDQhGyWNdCy49521vj6g',
    appId: '1:299534401118:ios:5c9ba44c8b8d376fed3ecf',
    messagingSenderId: '299534401118',
    projectId: 'prakflutterfirebase-1373c',
    storageBucket: 'prakflutterfirebase-1373c.appspot.com',
    iosBundleId: 'com.example.praktikum06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmxnIJmowzMq8l3bldYHLAaM1hNy2IzD4',
    appId: '1:299534401118:web:5421629acaee6b37ed3ecf',
    messagingSenderId: '299534401118',
    projectId: 'prakflutterfirebase-1373c',
    authDomain: 'prakflutterfirebase-1373c.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-1373c.appspot.com',
    measurementId: 'G-DEMTKDN7H1',
  );
}
